console.log('Hello')
console.log('Welcome to the practice workbook')
console.log('git add - fileName')
console.log('Save Changes: git commit -m "first commit"')
console.log('Push Changes: git push -u origin main ')